default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
    # - id: isort
    #   entry: isort
    #   name: isort
    #   language: system
    #   pass_filenames: true
    #   types:
    #     - python
        
    - entry: black
      id: black
      name: black
      language: system
      pass_filenames: true
      types:
        - python

    

    # - id: vulture
    #   name: vulture
    #   entry: vulture
    #   language: system
    #   files: "src/"
    #   description: Find unused Python code.
    #   pass_filenames: true
    #   types:
    #     - python
