name: scraper
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.10
  - bs4
  - pandas
  - requests
  - jupyter
  - black
  - isort
  - pre-commit
  - pip
  - vulture
  - pip:
    - makim==1.8.2
